installedApps:
  - git
developmentBranch: main
localStorageBranchTargets:
  features/dev/Jira0101: main
sfdxPluginsStdout: "sfdmu \e[2m4.30.0\e[22m\nsfdx-essentials \e[2m2.12.0\e[22m\nsfdx-git-delta \e[2m5.27.0\e[22m\nsfdx-hardis \e[2m4.8.1\e[22m\ntexei-sfdx-plugin \e[2m2.1.3\e[22m\n\e[2m\e[22m\n\e[2mUninstalled JIT Plugins:\e[22m\ncommunity \e[2m2.4.6\e[22m\ncustom-metadata \e[2m2.2.8\e[22m\ndev \e[2m1.2.1\e[22m\ndevops-center \e[2m1.2.3\e[22m\nenv \e[2m2.2.7\e[22m\nfunctions \e[2m1.22.3\e[22m\npackaging \e[2m1.26.4\e[22m\nsignups \e[2m1.5.5\e[22m\n@salesforce/sfdx-plugin-lwc-test \e[2m1.1.0\e[22m\n@salesforce/sfdx-scanner \e[2m3.17.0\e[22m\n"
